### ISSUE TITLE
update libflac with PS3 defines

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-deps#8]
This issue has its origins here: https://github.com/libretro/mame2003-plus-libretro/issues/622

The question is: Is it possible to either add PS3 support to libFLAC here without too much trouble, or can ifdefs be added to this version of libFLAC so that PS3 doesn't try to compile it?

**Comment by ghost** [comment]
I spoke to on discord earlier about this and bparker made a suggestion for defines. He has more experience than me with this sort of stuff but i dont think using linux glibc defines will work on the sdk i could be wrong.

for me the cleanest way to fix this is this

#if defined some ps3 identifier
#include <stdio.h> 
#endif

or add and extern ftello(); with the right parameters

to be clear this is just a warning its compiling fine.

**Comment by markwkidd** [comment]
I think buildbot uses a define like CELLOS for PS3

**Comment by ghost** [comment]
again there will be no log to check now it compiles it was just a warning someone on the buildbot will need to do it and test

**Comment by markwkidd** [comment]
at @twinaphex 
 request I'm going to port this commit to libflac which should resolve the issue https://github.com/libretro/tyrquake/commit/010564ab552f6e9ffb8ea1e0ff0f200989121689#diff-27f979b5342a765fc816f2b3257ec921

**Comment by markwkidd** [comment]
fixed https://github.com/libretro/libretro-deps/pull/9
